on:
  pull_request:
    types: [opened, synchronize]
jobs:
  evaluator_job:
    name: Evaluator Job
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Evaluator step
        id: evaluator
        uses: betrybe/jest-evaluator-action@v6
        with:
          repository-test-name: 'betrybe/testecomRenatoeAna-testes'
          repository-test-branch: 'main'
          npm-start: true
      - name: Store evaluation step
        uses: betrybe/store-evaluation-action@v2
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          environment: production
          pr-number: ${{ github.event.number }}
